#!/bin/bash
#Copyright 2016 Kenta Ishii All Rights Reserved.
#This Software is under GNU GPL (General Public License) Version 3
#This Shell Script is for Raspbian Jessie on Raspberry Pi 2 Model B and licensed under GNU License.
#Written by Kenta Ishii, Tokyo.
#Make sure to change permissions of this file. e.g. chmod 0744 gpiomonitor
#If you meet any freezen shell, interrupt through ctrl+c or so...
#CAUTION! This software and Kenta Ishii are exempt from all warranty and all compensation caused by all damage as a result of using this software.

source gpiocomm --functions

echo "Start Monitoring GPIO..."

while :
do
    date +%Hh-%Mm-%Ss-%Nns
    gpio_list
    #Speed is slow, even you set 0.01.
    sleep 0.5
done
